#include "main.h" // IWYU pragma: keep
#include "Helix/auton_selector.hpp"
#include <algorithm>
#include <cstdint>
#include <cstdio>

using namespace Helix;

// ── Colors ───────────────────────────────────────────────────────────────────
#define C_BG        lv_color_hex(0x0D0D0D)
#define C_PANEL     lv_color_hex(0x141414)
#define C_CARD      lv_color_hex(0x1A1A1A)
#define C_CARD_SEL  lv_color_hex(0x12121F)
#define C_ACCENT    lv_color_hex(0x0044BB)
#define C_RED       lv_color_hex(0xCC3333)
#define C_BLUE      lv_color_hex(0x3333CC)
#define C_WHITE     lv_color_hex(0xFFFFFF)
#define C_GREY      lv_color_hex(0x666666)
#define C_LGREY     lv_color_hex(0xAAAAAA)
#define C_DIVIDER   lv_color_hex(0x222222)
#define C_GREEN     lv_color_hex(0x44CC88)

// ── Helpers ───────────────────────────────────────────────────────────────────
static lv_obj_t* make_rect(lv_obj_t* parent, int x, int y, int w, int h, lv_color_t color) {
    lv_obj_t* obj = lv_obj_create(parent);
    lv_obj_set_pos(obj, x, y);
    lv_obj_set_size(obj, w, h);
    lv_obj_set_style_bg_color(obj, color, 0);
    lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(obj, 0, 0);
    lv_obj_set_style_pad_all(obj, 0, 0);
    lv_obj_set_style_radius(obj, 0, 0);
    lv_obj_remove_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    return obj;
}

static lv_obj_t* make_label(lv_obj_t* parent, int x, int y, const char* text,
                             lv_color_t color, bool large = false) {
    lv_obj_t* label = lv_label_create(parent);
    lv_label_set_text(label, text);
    lv_obj_set_style_text_color(label, color, 0);
    lv_obj_set_style_text_font(label, large ? &lv_font_montserrat_16 : &lv_font_montserrat_12, 0);
    lv_obj_set_pos(label, x, y);
    // Transparent background — no set_style_bg needed, labels default transparent
    return label;
}

// ── Declare the image from your converted C file ──────────────────────────────
// Make sure the name in the parentheses matches the name generated by the converter
// ── Declare the image with C-linkage so C++ can see it ────────────────────────
extern "C" {
    extern const lv_image_dsc_t Field;
}

// ── Draw field (left panel) ───────────────────────────────────────────────────
// ── Draw field (left panel) ───────────────────────────────────────────────────
// ── Draw field (left panel) ───────────────────────────────────────────────────
static void draw_field(lv_obj_t* parent, bool highlight_red) {
    // 1. Draw the field image
    lv_obj_t* img = lv_image_create(parent);
    lv_image_set_src(img, &Field);
    lv_obj_set_pos(img, 8, 8);

    // 2. Set up overlay colors (semi-transparent)
    lv_color_t red_zone   = highlight_red  ? lv_color_hex(0xCC0000) : lv_color_hex(0x440000);
    lv_color_t blue_zone  = !highlight_red ? lv_color_hex(0x0000CC) : lv_color_hex(0x000044);
    
    // Slightly see-through so the underlying image details are visible
    lv_opa_t opacity = LV_OPA_50; 

    // 3. Draw Starting Zones (Proportioned to ~26x26 pixels)
    
    // --- RED SIDE ---
    // Middle-Left Red
    lv_obj_t* r_ml = make_rect(parent, 8, 87, 26, 26, red_zone);
    lv_obj_set_style_bg_opa(r_ml, opacity, 0);
    lv_obj_set_style_border_color(r_ml, C_RED, 0);
    lv_obj_set_style_border_width(r_ml, 1, 0);

    // Middle-Bottom Red (New!)
    lv_obj_t* r_mb = make_rect(parent, 87, 166, 26, 26, red_zone);
    lv_obj_set_style_bg_opa(r_mb, opacity, 0);
    lv_obj_set_style_border_color(r_mb, C_RED, 0);
    lv_obj_set_style_border_width(r_mb, 1, 0);

    // --- BLUE SIDE ---
    // Middle-Right Blue
    lv_obj_t* b_mr = make_rect(parent, 166, 87, 26, 26, blue_zone);
    lv_obj_set_style_bg_opa(b_mr, opacity, 0);
    lv_obj_set_style_border_color(b_mr, C_BLUE, 0);
    lv_obj_set_style_border_width(b_mr, 1, 0);

    // Middle-Top Blue (New!)
    lv_obj_t* b_mt = make_rect(parent, 87, 8, 26, 26, blue_zone);
    lv_obj_set_style_bg_opa(b_mt, opacity, 0);
    lv_obj_set_style_border_color(b_mt, C_BLUE, 0);
    lv_obj_set_style_border_width(b_mt, 1, 0);

    // Label
    make_label(parent, 14, 198, "Override", C_GREY);
}

// ── Constructors ──────────────────────────────────────────────────────────────
AutonSelector::AutonSelector() {
    auton_count = 0;
    auton_page_current = 0;
    current_view = SelectorView::LIST;
    screen = nullptr;
    Autons = {};
}

AutonSelector::AutonSelector(std::vector<Auton> autons) {
    auton_count = autons.size();
    auton_page_current = 0;
    current_view = SelectorView::LIST;
    screen = nullptr;
    Autons.assign(autons.begin(), autons.end());
}

void AutonSelector::autons_add(std::vector<Auton> autons) {
    Autons.insert(Autons.end(), autons.begin(), autons.end());
    auton_count = static_cast<int>(Autons.size());
    auton_page_current = 0;
}

void AutonSelector::selected_auton_call() {
    if (auton_count == 0) return;
    auton_page_current = std::clamp(auton_page_current, 0, auton_count - 1);
    if (!Autons[auton_page_current].auton_call) return;
    Autons[auton_page_current].auton_call();
}

// ── Init: build the full UI once ──────────────────────────────────────────────
void AutonSelector::init_ui() {
    screen = lv_obj_create(NULL);
    lv_screen_load(screen);
    lv_obj_set_style_bg_color(screen, C_BG, 0);
    lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
    show_list();
}

// ── LIST VIEW ─────────────────────────────────────────────────────────────────
void AutonSelector::show_list() {
    current_view = SelectorView::LIST;

    if (auton_count == 0) {
        if (screen == nullptr) return;
        lv_obj_clean(screen);
        make_label(screen, 24, 96, "NO AUTONOMOUS ROUTINES", C_WHITE, true);
        make_label(screen, 24, 122, "Add a routine before initializing the selector.", C_GREY);
        return;
    }

    // Clear screen
    lv_obj_delete(screen);
    screen = lv_obj_create(NULL);
    lv_screen_load(screen);
    lv_obj_set_style_bg_color(screen, C_BG, 0);
    lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);

    // ── Left panel ────────────────────────────────────────────────────────────
    lv_obj_t* left = make_rect(screen, 0, 0, 200, 240, C_PANEL);
    draw_field(left, Autons[auton_page_current].IsRed);

    // ── Divider ───────────────────────────────────────────────────────────────
    make_rect(screen, 200, 0, 2, 240, C_DIVIDER);

    // ── Right panel ───────────────────────────────────────────────────────────
    lv_obj_t* right = make_rect(screen, 202, 0, 278, 240, C_PANEL);

    // Header bar
    lv_obj_t* header = make_rect(right, 0, 0, 278, 30, lv_color_hex(0x161616));
    make_label(header, 10, 8, "SELECT AUTONOMOUS", C_GREY);

    // Page counter badge
    lv_obj_t* badge = make_rect(header, 220, 5, 50, 20, C_ACCENT);
    char pg[16];
    snprintf(pg, sizeof(pg), "%d / %d", auton_page_current + 1, auton_count);
    make_label(badge, 6, 3, pg, C_WHITE);

    // Navigation controls keep routines beyond the first four reachable.
    lv_obj_t* previous = make_rect(header, 174, 5, 20, 20, C_CARD);
    make_label(previous, 6, 2, "<", C_LGREY, true);
    lv_obj_add_flag(previous, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(previous, [](lv_event_t* e) {
        if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
        AutonSelector* selector = static_cast<AutonSelector*>(lv_event_get_user_data(e));
        selector->auton_page_current = std::max(0, selector->auton_page_current - 1);
        selector->show_list();
    }, LV_EVENT_CLICKED, this);

    lv_obj_t* next = make_rect(header, 198, 5, 20, 20, C_CARD);
    make_label(next, 6, 2, ">", C_LGREY, true);
    lv_obj_add_flag(next, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(next, [](lv_event_t* e) {
        if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
        AutonSelector* selector = static_cast<AutonSelector*>(lv_event_get_user_data(e));
        selector->auton_page_current = std::min(selector->auton_count - 1,
                                                 selector->auton_page_current + 1);
        selector->show_list();
    }, LV_EVENT_CLICKED, this);

    // Accent line
    make_rect(right, 0, 30, 278, 2, C_ACCENT);

    // ── Auton cards ───────────────────────────────────────────────────────────
    int scroll_offset = (auton_page_current >= 4) ? auton_page_current - 3 : 0;
    int visible = std::min(4, auton_count);

    for (int i = 0; i < visible && (i + scroll_offset) < auton_count; i++) {
        int idx = i + scroll_offset;
        bool sel = (idx == auton_page_current);
        int cy = 34 + i * 50;

        // Card background
        lv_obj_t* card = make_rect(right, 6, cy, 262, 46, sel ? C_CARD_SEL : C_CARD);
        lv_obj_set_style_border_color(card, sel ? C_ACCENT : C_DIVIDER, 0);
        lv_obj_set_style_border_width(card, 1, 0);
        lv_obj_set_style_radius(card, 3, 0);

        // Color sidebar
        make_rect(card, 0, 0, 4, 46, Autons[idx].IsRed ? C_RED : C_BLUE);

        // Name
        make_label(card, 10, 6, Autons[idx].Name.c_str(),
                   sel ? C_WHITE : C_LGREY, true);

        // Description preview
        std::string preview = Autons[idx].Description.substr(0, 35);
        if (Autons[idx].Description.length() > 35) preview += "...";
        make_label(card, 10, 26, preview.c_str(), C_GREY);

        // Arrow on selected
        if (sel) make_label(card, 248, 12, ">", C_ACCENT, true);

        // Touch callback — capture idx
        lv_obj_add_flag(card, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_user_data(card, (void*)(intptr_t)idx);
        lv_obj_add_event_cb(card, [](lv_event_t* e) {
            if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
                AutonSelector* sel_ptr = (AutonSelector*)lv_event_get_user_data(e);
                int tapped = (int)(intptr_t)lv_obj_get_user_data((lv_obj_t*)lv_event_get_target(e));
                sel_ptr->auton_page_current = tapped;
                sel_ptr->show_detail(tapped);
            }
        }, LV_EVENT_CLICKED, this);
    }

    // Scrollbar
    if (auton_count > 4) {
        make_rect(right, 270, 32, 4, 206, lv_color_hex(0x1A1A1A));
        int bar_h = (4 * 206) / auton_count;
        int bar_y = 32 + (scroll_offset * 206) / auton_count;
        make_rect(right, 270, bar_y, 4, bar_h, C_GREY);
    }

    // Bottom accent
    make_rect(right, 0, 236, 278, 4, C_ACCENT);
}

// ── DETAIL VIEW ───────────────────────────────────────────────────────────────
void AutonSelector::show_detail(int index) {
    if (auton_count == 0 || index < 0 || index >= auton_count) return;
    current_view = SelectorView::DETAIL;
    Auton& a = Autons[index];

    // Clear screen
    lv_obj_delete(screen);
    screen = lv_obj_create(NULL);
    lv_screen_load(screen);
    lv_obj_set_style_bg_color(screen, C_BG, 0);
    lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);

    // ── Left panel with highlighted zone ─────────────────────────────────────
    lv_obj_t* left = make_rect(screen, 0, 0, 200, 240, C_PANEL);
    draw_field(left, a.IsRed);

    // ── Divider ───────────────────────────────────────────────────────────────
    make_rect(screen, 200, 0, 2, 240, C_DIVIDER);

    // ── Right panel ───────────────────────────────────────────────────────────
    lv_obj_t* right = make_rect(screen, 202, 0, 278, 240, C_PANEL);

    // Back button
    lv_obj_t* back_btn = make_rect(right, 6, 8, 60, 22, lv_color_hex(0x1A1A1A));
    lv_obj_set_style_border_color(back_btn, C_DIVIDER, 0);
    lv_obj_set_style_border_width(back_btn, 1, 0);
    lv_obj_set_style_radius(back_btn, 3, 0);
    make_label(back_btn, 8, 4, "< back", C_LGREY);
    lv_obj_add_flag(back_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(back_btn, [](lv_event_t* e) {
        if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
            AutonSelector* s = (AutonSelector*)lv_event_get_user_data(e);
            s->show_list();
        }
    }, LV_EVENT_CLICKED, this);

    // Color badge
    lv_obj_t* badge = make_rect(right, 210, 8, 56, 22, a.IsRed ? C_RED : C_BLUE);
    lv_obj_set_style_radius(badge, 3, 0);
    make_label(badge, 10, 4, a.IsRed ? "RED" : "BLUE", C_WHITE);

    // Auton name
    make_label(right, 6, 36, a.Name.c_str(), C_WHITE, true);

    // Divider under name
    make_rect(right, 6, 56, 266, 1, C_DIVIDER);

    // ── Create Content Container ─────────────────────────────────────────────
    // Reverted width to 266px since arrow buttons are gone!
    lv_obj_t* scroll_container = lv_obj_create(right);
    lv_obj_set_pos(scroll_container, 0, 60);
    lv_obj_set_size(scroll_container, 266, 126);
    
    // Default: Assume everything fits nicely and disable scrolling
    lv_obj_set_style_bg_opa(scroll_container, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(scroll_container, 0, 0);
    lv_obj_set_scrollbar_mode(scroll_container, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(scroll_container, LV_DIR_NONE);

    // Default compact padding
    lv_obj_set_style_pad_left(scroll_container, 8, 0);
    lv_obj_set_style_pad_right(scroll_container, 8, 0);
    lv_obj_set_style_pad_top(scroll_container, 2, 0);
    lv_obj_set_style_pad_bottom(scroll_container, 4, 0); 

    // ── Scroll Content with Tighter Spacing & Proper Internal Gaps ────────────
    
    // 1. DESCRIPTION
    lv_obj_t* desc_header = make_label(scroll_container, 0, 0, "DESCRIPTION", C_GREY);
    
    // Description text (Roomier 18px gap below the header)
    lv_obj_t* desc_label = make_label(scroll_container, 0, 18, a.Description.c_str(), C_LGREY);
    lv_obj_set_width(desc_label, 240); // Max width utilizing the full panel width
    lv_label_set_long_mode(desc_label, LV_LABEL_LONG_WRAP);

    // 2. ALLIANCE (Distance from bottom of previous text to header remains at +8px)
    int alliance_y = lv_obj_get_y(desc_label) + lv_obj_get_height(desc_label) + 8;
    if (alliance_y < 45) alliance_y = 45;

    lv_obj_t* alliance_header = make_label(scroll_container, 0, alliance_y, "ALLIANCE", C_GREY);
    
    // Alliance value (Roomier 18px gap below the header)
    lv_obj_t* alliance_val = make_label(scroll_container, 0, alliance_y + 18, a.IsRed ? "Red Alliance" : "Blue Alliance",
                                        a.IsRed ? C_RED : C_BLUE, true);
               
    // 3. EXPECTED POINTS (Distance from bottom of previous text to header remains at +8px)
    int pts_y = alliance_y + 38; 
    lv_obj_t* pts_header = make_label(scroll_container, 0, pts_y, "EXPECTED POINTS", C_GREY);
    
    // Points box (Roomier 18px gap below the header)
    lv_obj_t* pts_box = make_rect(scroll_container, 0, pts_y + 18, 80, 22, lv_color_hex(0x1A2A1A));
    lv_obj_set_style_radius(pts_box, 3, 0);

    char pts_str[16];
    snprintf(pts_str, sizeof(pts_str), "+%d pts", a.ExpectedPoints);
    make_label(pts_box, 8, 3, pts_str, C_GREEN);


    // ── Auto-Detect Content Height Overflow ──────────────────────────────────
    // Calculate the absolute lowest vertical boundary used by the points box
    int lowest_y = pts_y + 18 + 22; // Header start + internal gap + box height

    if (lowest_y > 126) {
        // Content overflows past our 126px boundary! Turn on touch scroll.
        lv_obj_set_scrollbar_mode(scroll_container, LV_SCROLLBAR_MODE_AUTO);
        lv_obj_set_scroll_dir(scroll_container, LV_DIR_VER);
        
        // Adjust padding to leave space for the scroll bar and bottom buffer
        lv_obj_set_style_pad_right(scroll_container, 14, 0);
        lv_obj_set_style_pad_bottom(scroll_container, 15, 0);

        // Chain child touch events to parent scroll so dragging still registers smoothly
        lv_obj_add_flag(desc_header, LV_OBJ_FLAG_SCROLL_CHAIN);
        lv_obj_add_flag(desc_label, LV_OBJ_FLAG_SCROLL_CHAIN);
        lv_obj_add_flag(alliance_header, LV_OBJ_FLAG_SCROLL_CHAIN);
        lv_obj_add_flag(alliance_val, LV_OBJ_FLAG_SCROLL_CHAIN);
        lv_obj_add_flag(pts_header, LV_OBJ_FLAG_SCROLL_CHAIN);
        lv_obj_add_flag(pts_box, LV_OBJ_FLAG_SCROLL_CHAIN);
    }


    // ── Confirm button (Static at bottom) ───────────────────────────────────
    lv_obj_t* confirm = make_rect(right, 6, 192, 266, 40, C_ACCENT);
    lv_obj_set_style_radius(confirm, 4, 0);
    make_label(confirm, 60, 12, "CONFIRM SELECTION", C_WHITE, true);
    lv_obj_add_flag(confirm, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(confirm, [](lv_event_t* e) {
        if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
            AutonSelector* s = (AutonSelector*)lv_event_get_user_data(e);
            lv_obj_t* btn = (lv_obj_t*)lv_event_get_target(e);
            lv_obj_set_style_bg_color(btn, lv_color_hex(0x44CC88), 0);
            lv_obj_t* lbl = (lv_obj_t*)lv_obj_get_child(btn, 0);
            if (lbl) lv_label_set_text(lbl, "CONFIRMED!");
            pros::Task([](void* param) {
                pros::delay(600);
                ((AutonSelector*)param)->show_list();
                pros::Task::current().remove();
            }, s, "confirm_flash");
        }
    }, LV_EVENT_CLICKED, this);

    // Bottom accent
    make_rect(right, 0, 236, 278, 4, C_ACCENT);
}

// Legacy — keep so existing call in main.cpp still compiles
void Helix::AutonSelector::selected_auton_print() {
    init_ui();
}
